language: generic
sudo: false
git:
  depth: 1

matrix:
  include:
    - os: linux

script:
  - pwd
  - echo 'travis_fold:start:setup_latest_vim'
  - sudo apt-get update
  - sudo apt-get install -y git build-essential libncursesw5-dev
  - git clone --depth 1 https://github.com/vim/vim.git
  - make -C vim || cat vim/src/auto/config.log
  - echo 'travis_fold:end:setup_latest_vim'
  - ./vim/src/vim --version
  - ./vim/src/vim -u NONE -N --noplugin --not-a-term -c "set rtp+=." -c "call jumptoline#run_tests()" -c "qa!"
  - if test -f test.log; then exit 1; fi

